In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

%matplotlib inline

In [2]:
df1 = pd.read_csv('Youtube01-Psy.csv')

In [3]:
df1.info

<bound method DataFrame.info of                                       COMMENT_ID  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
..                                           ...   
345            z13th1q4yzihf1bll23qxzpjeujterydj   
346        z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k   
347          z130zd5b3titudkoe04ccbeohojxuzppvbg   
348          z12he50arvrkivl5u04cctawgxzkjfsjcc4   
349        z13vhvu54u3ewpp5h04ccb4zuoardrmjlyk0k   

                                   AUTHOR                 DATE  \
0                               Julius NM  2013-11-07T06:20:48   
1                             adam riyati  2013-11-07T12:37:15   
2                        Evgeny Murashkin  2013-11-08T17:34:21   
3                         ElNino Melendez  2013-11-09T08:28:43   
4            

In [4]:
df2 = pd.read_csv('Youtube02-KatyPerry.csv')
df3 = pd.read_csv('Youtube03-LMFAO.csv')
df4 = pd.read_csv('Youtube04-Eminem.csv')
df5 = pd.read_csv('Youtube05-Shakira.csv')

In [5]:
df = pd.concat([df1,df2,df3,df4,df5])
df

COMMENT_ID                AUTHOR  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
..                                           ...                   ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                           DATE  \
0           2013-11-07T06:20:48   
1           2013-11-07T12:37:15   
2           2013-11-08T17:34:21   
3           2013-11-09T08:28:43   
4           2013-11-10T16:05:38   
..                          ...   
365  2013-07-13T13:27:39.441000   
366  2013-07-13T13:14:30.021000   
367  2013-07-13T12:09:31.188000   
368  2013-07-13T11:17:52.308000   
369  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [6]:
df.shape

(1956, 5)

In [7]:
keys = ['Psy', 'Katy Perry', 'LMFAO', 'Eminem', 'Shakira']

In [8]:
df_with_keys = pd.concat([df1,df2,df3,df4,df5], keys=keys)
df_with_keys #this adds the names as the key or index

COMMENT_ID  \
Psy     0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
        1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
        2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
        3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
        4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
...                                                  ...   
Shakira 365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
        366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
        367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
        368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
        369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                           AUTHOR                        DATE  \
Psy     0               Julius NM         2013-11-07T06:20:48   
        1             adam riyati         2013-11-07T12:37:15   
        2        Evgeny Murashkin         2013-11-08T17:34:21   
        3         ElNino Melendez         2013-11-09T08:28:43   
        4                  GsMega         2013-11-10T16:05:38   
...                           ...                         ...   
Shakira 365          Katie Mettam  2013-07-13T13:27:39.441000   
        366  Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
        367         jeffrey jules  2013-07-13T12:09:31.188000   
        368        Aishlin Maciel  2013-07-13T11:17:52.308000   
        369           Latin Bosch  2013-07-12T22:33:27.916000   

                                                       CONTENT  CLASS  
Psy     0    Huh, anyway check out this you[tube] channel: ...      1  
        1    Hey guys check out my new channel and our firs...      1  
        2               just for test I have to say murdev.com      1  
        3     me shaking my sexy ass on my channel enjoy ^_^       1  
        4              watch?v=vtaRGgvGtWQ   Check this out .      1  
...                                                        ...    ...  
Shakira 365  I love this song because we sing it at Camp al...      0  
        366  I love this song for two reasons: 1.it is abou...      0  
        367                                                wow      0  
        368                            Shakira u are so wiredo      0  
        369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [9]:
df_with_keys.loc['Shakira'] #only Shakira

COMMENT_ID  \
0            z13lgffb5w3ddx1ul22qy1wxspy5cpkz504   
1              z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj   
2          z12quxxp2vutflkxv04cihggzt2azl34pms0k   
3              z12icv3ysqvlwth2c23eddlykyqut5z1h   
4              z133stly3kete3tly22petvwdpmghrlli   
..                                           ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                                 AUTHOR                        DATE  \
0                            dharma pal  2015-05-29T02:30:18.971000   
1                         Tiza Arellano  2015-05-29T00:14:48.748000   
2    Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™   2015-05-28T21:00:08.607000   
3                         Eric Gonzalez  2015-05-28T20:47:12.193000   
4                         Analena López  2015-05-28T17:08:29.827000   
..                                  ...                         ...   
365                        Katie Mettam  2013-07-13T13:27:39.441000   
366                Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
367                       jeffrey jules  2013-07-13T12:09:31.188000   
368                      Aishlin Maciel  2013-07-13T11:17:52.308000   
369                         Latin Bosch  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0                                           Nice song      0  
1                                        I love song       0  
2                                        I love song       0  
3    860,000,000 lets make it first female to reach...      0  
4                        shakira is best for worldcup      0  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[370 rows x 5 columns]

In [10]:
#convert merged data to a csv file
df_with_keys.to_csv('YouTube_Merged_Data.csv')

In [11]:
df = df_with_keys
df

COMMENT_ID  \
Psy     0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
        1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
        2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
        3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
        4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
...                                                  ...   
Shakira 365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
        366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
        367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
        368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
        369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                           AUTHOR                        DATE  \
Psy     0               Julius NM         2013-11-07T06:20:48   
        1             adam riyati         2013-11-07T12:37:15   
        2        Evgeny Murashkin         2013-11-08T17:34:21   
        3         ElNino Melendez         2013-11-09T08:28:43   
        4                  GsMega         2013-11-10T16:05:38   
...                           ...                         ...   
Shakira 365          Katie Mettam  2013-07-13T13:27:39.441000   
        366  Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
        367         jeffrey jules  2013-07-13T12:09:31.188000   
        368        Aishlin Maciel  2013-07-13T11:17:52.308000   
        369           Latin Bosch  2013-07-12T22:33:27.916000   

                                                       CONTENT  CLASS  
Psy     0    Huh, anyway check out this you[tube] channel: ...      1  
        1    Hey guys check out my new channel and our firs...      1  
        2               just for test I have to say murdev.com      1  
        3     me shaking my sexy ass on my channel enjoy ^_^       1  
        4              watch?v=vtaRGgvGtWQ   Check this out .      1  
...                                                        ...    ...  
Shakira 365  I love this song because we sing it at Camp al...      0  
        366  I love this song for two reasons: 1.it is abou...      0  
        367                                                wow      0  
        368                            Shakira u are so wiredo      0  
        369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [12]:
df.size

9780

In [13]:
df.columns

Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='object')

In [14]:
df.dtypes

COMMENT_ID    object
AUTHOR        object
DATE          object
CONTENT       object
CLASS          int64
dtype: object

In [15]:
df.isnull().sum()

COMMENT_ID      0
AUTHOR          0
DATE          245
CONTENT         0
CLASS           0
dtype: int64

In [16]:
df.isnull().isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [17]:
df.DATE

Psy      0             2013-11-07T06:20:48
         1             2013-11-07T12:37:15
         2             2013-11-08T17:34:21
         3             2013-11-09T08:28:43
         4             2013-11-10T16:05:38
                           ...            
Shakira  365    2013-07-13T13:27:39.441000
         366    2013-07-13T13:14:30.021000
         367    2013-07-13T12:09:31.188000
         368    2013-07-13T11:17:52.308000
         369    2013-07-12T22:33:27.916000
Name: DATE, Length: 1956, dtype: object

In [18]:
df.AUTHOR

Psy      0                 Julius NM
         1               adam riyati
         2          Evgeny Murashkin
         3           ElNino Melendez
         4                    GsMega
                        ...         
Shakira  365            Katie Mettam
         366    Sabina Pearson-Smith
         367           jeffrey jules
         368          Aishlin Maciel
         369             Latin Bosch
Name: AUTHOR, Length: 1956, dtype: object

In [19]:
# Convert the Author Name to First Name and Last Name
#df["FIRSTNAME"] = df['AUTHOR'].str.split(' ').str[0].to_list
#df.FIRSTNAME

In [20]:
df_data = df[['CONTENT', 'CLASS']]
df_data

CONTENT  CLASS
Psy     0    Huh, anyway check out this you[tube] channel: ...      1
        1    Hey guys check out my new channel and our firs...      1
        2               just for test I have to say murdev.com      1
        3     me shaking my sexy ass on my channel enjoy ^_^       1
        4              watch?v=vtaRGgvGtWQ   Check this out .      1
...                                                        ...    ...
Shakira 365  I love this song because we sing it at Camp al...      0
        366  I love this song for two reasons: 1.it is abou...      0
        367                                                wow      0
        368                            Shakira u are so wiredo      0
        369                         Shakira is the best dancer      0

[1956 rows x 2 columns]

In [21]:
x = df_data.CONTENT
y = df_data.CLASS

In [22]:
cv = CountVectorizer() #The CountVectorizer provides a simple way to both tokenize a collection of text documents and build a vocabulary of known words, but also to encode new documents using that vocabulary. 
ex = cv.fit_transform(["Great song but check this out","What is this song?"])

In [23]:
ex.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=int64)

In [24]:
cv.get_feature_names()

['but', 'check', 'great', 'is', 'out', 'song', 'this', 'what']

In [25]:
cv = CountVectorizer()
corpus = x
X = cv.fit_transform(corpus)

In [26]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
X.shape

(1956, 4454)

In [28]:
X.size

25765

In [29]:
cv.get_feature_names()

['00',
 '000',
 '002',
 '018',
 '02',
 '034',
 '04',
 '047000',
 '05',
 '053012',
 '0687119038',
 '08',
 '09',
 '0cb8qfjaa',
 '0d878a889c',
 '0dbhjzdw0lbsjbi40gxm0d0p5krhv8xinqli53__wqbahs8zx4mjhw5vwrkpxfoeks',
 '0laviqu2b',
 '10',
 '100',
 '1000',
 '10000000',
 '1000000000',
 '100000415527985',
 '100005244783212',
 '100007085325116',
 '10001',
 '100877300245414',
 '101721377578919894134',
 '10200253113705769',
 '1030',
 '104999962146104962510',
 '10626048',
 '10626835',
 '106865403',
 '107297364',
 '1073741825',
 '1073741828',
 '1073741830',
 '1073741943',
 '108k',
 '109',
 '10b35481',
 '11',
 '1111',
 '1111111111111111111',
 '111719098841907',
 '111982027348137311818',
 '112720997191206369631',
 '11cpwb',
 '11th',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '128gb',
 '12year',
 '13',
 '13017194',
 '131275322914',
 '131338190916',
 '1337',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '134

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
print(X_train.size)
print(X_test.size)
print(y_train.size)
print(y_test.size)

17525
8240
1310
646


In [32]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1310, 4454)
(646, 4454)
(1310,)
(646,)


In [33]:
X_train

<1310x4454 sparse matrix of type '<class 'numpy.int64'>'
	with 17525 stored elements in Compressed Sparse Row format>

In [34]:
#IMPLEMENTING NAIVE-BAYES CLASSIFIER
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)


MultinomialNB()

In [36]:
print(clf.intercept_)
print(clf.coef_)
print(clf.classes_)
print(clf.score(X_train, y_train))

[-0.67349424]
[[-9.88308074 -6.93864176 -9.88308074 ... -9.88308074 -9.88308074
  -9.88308074]]
[0 1]
0.9618320610687023


In [37]:
print(clf.score(X_test, y_test))

0.9195046439628483


In [38]:
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 91.95046439628483 %


In [39]:
pred = clf.predict(X_test)
pred

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

In [40]:
#Try your own comment
comment = ["Check this out"]
vec = cv.transform(comment)
vec

<1x4454 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [41]:
vec = cv.transform(comment).toarray()

In [42]:
vec

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
clf.predict(vec)

array([1], dtype=int64)

In [50]:
dic = {'ham':0, 'spam':1}
dic.values()

dict_values([0, 1])

In [51]:
if clf.predict(vec)==1:
    print('Spam')
else:
    print('Ham')

Spam


In [56]:
eg = ['How have you been?']
v = cv.transform(eg).toarray()

In [57]:
eg

['How have you been?']

In [58]:
v

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [59]:
clf.predict(v)

array([1], dtype=int64)

In [60]:
eg1 = ['Great song man!']
v2 = cv.transform(eg1).toarray()
clf.predict(v2)

array([0], dtype=int64)

In [61]:
#SAVING THE MODEL

import pickle

In [62]:
naiveBayes = open('YTSpamHam.pkl', 'wb')
pickle.dump(clf, naiveBayes)

In [63]:
naiveBayes.close()

In [64]:
#LOAD MODEL
new_model = pickle.load(open('YTSpamHam.pkl', 'rb'))
new_model

MultinomialNB()

In [65]:
#Try another sample
eg2 = ['Hey Music Fans I really appreciate all of you,but see this song too']
v2 = cv.transform(eg2).toarray()
new_model.predict(v2)

array([1], dtype=int64)

In [67]:
if new_model.predict(v2) == 1:
    print("Spam")
else:
    print("Ham")

Spam


In [68]:
#Try another sample
eg3 = ['Hey Music Fans I really appreciate all of you,but I gotta go study right now']
v3 = cv.transform(eg3).toarray()
if new_model.predict(v3) == 1:
    print('Spam')
else:
    print('Ham')


Spam
