## Linear Algebra in Python

In [2]:
#Defining two vectors 
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)

x: [1 2 3 4]
y: [5 6 7 8]


We can now calculate the $dot$ or $inner product$ using the dot function of numpy:

In [3]:
np.dot(x, y)

70

Note that both vectors are actually row vectors in the above code. We can transpose them to column vectors by using the shape property:

In [4]:
print("x:", x)
x.shape = (4, 1)
print("xT:", x)
print("y:", y)
y.shape = (4, 1)
print("yT:", y)

x: [1 2 3 4]
xT: [[1]
 [2]
 [3]
 [4]]
y: [5 6 7 8]
yT: [[5]
 [6]
 [7]
 [8]]


Usually, we can transform a row vector into a column vector in numpy by using the T method on vector or matrix objects:

In [6]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)

x: [1 2 3 4]
y: [5 6 7 8]
xT: [1 2 3 4]
yT: [5 6 7 8]


The problem here is that this does not do, what we expect it to do. It only works, if we declare the variables not to be arrays of numbers, but in fact a matrix:

In [7]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
print("x:", x)
print("y:", y)
print("xT:", x.T)
print("yT:", y.T)

x: [[1 2 3 4]]
y: [[5 6 7 8]]
xT: [[1]
 [2]
 [3]
 [4]]
yT: [[5]
 [6]
 [7]
 [8]]


One can also use Reshape funtion 

In [8]:
x = np.array([[1, 2, 3, 4]])
print("x:", x)
print("xT:", np.reshape(x, (4, 1)))
print("xT:", x.T)
print("xT:", x.transpose())

x: [[1 2 3 4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]


Product of two matrix 

In [9]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[5, 6, 7, 8]])
x.T * y

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

Matrix mutiplication with Scalar

In [11]:
import numpy as np
A = np.array([[4, 5, 6],
             [7, 8, 9]])
A * 2

array([[ 8, 10, 12],
       [14, 16, 18]])

Inverse of matrix

In [14]:
A = np.array([[4, 5, 6],
             [7, 8, 9],
              [2, 5, 6]])
np.linalg.inv(A)

array([[ 0.5       ,  0.        , -0.5       ],
       [-4.        ,  2.        ,  1.        ],
       [ 3.16666667, -1.66666667, -0.5       ]])

Representing imgaes in Array

In [15]:
from PIL import Image
  
  
# sample.png is the name of the image
# file and assuming that it is uploaded
# in the current directory or we need
# to give the path
image = Image.open('berlin.jpg')
  
# summarize some details about the image
print(image.format)
print(image.size)
print(image.mode)

JPEG
(1280, 720)
RGB


In [17]:
numpydata = np.asarray(image)
  
# <class 'numpy.ndarray'>
print(type(numpydata))
  
#  shape: 3 because it is colour image i.e. 3 Channel Image RGB
print(numpydata.shape)

<class 'numpy.ndarray'>
(720, 1280, 3)


In [18]:
print(numpydata)

[[[  6  27 136]
  [  6  27 136]
  [  6  27 136]
  ...
  [  5  30 157]
  [  5  30 157]
  [  5  30 157]]

 [[  6  27 136]
  [  6  27 136]
  [  6  27 136]
  ...
  [  5  30 157]
  [  5  30 157]
  [  5  30 157]]

 [[  6  27 136]
  [  6  27 136]
  [  6  27 136]
  ...
  [  5  30 157]
  [  5  30 157]
  [  5  30 157]]

 ...

 [[234 206 169]
  [224 196 159]
  [202 174 137]
  ...
  [160 132 120]
  [161 133 121]
  [159 131 119]]

 [[214 186 149]
  [215 187 150]
  [207 179 142]
  ...
  [157 129 117]
  [166 138 126]
  [173 145 133]]

 [[225 197 160]
  [231 203 166]
  [238 210 173]
  ...
  [157 129 115]
  [160 132 118]
  [163 135 121]]]
