In [85]:
from numpy import *
from numpy.linalg import *

In [5]:
#random array
y=int(input())
x=random.random(y)
print(x)

4
[0.35044377 0.33760849 0.90457165 0.19929677]


In [6]:
#power
x,y=2,3
z=power(x,y)
print(z)

8


In [10]:
#array using list
list=[1,2,3,4,5]
x=array(list)
print(x)

[1 2 3 4 5]


In [12]:
#sin x , cos x
x=1
print(sin(x))
print(cos(x))

0.8414709848078965
0.5403023058681398


In [16]:
#range function of array
arr=arange(1,51,10) #not include end value
print(arr)

[ 1 11 21 31 41]


In [17]:
#linspace
arr=linspace(1,100,10) #include end value
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [22]:
#data-type
arr=array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64


In [28]:
#dimension
arr1=array([[1,2,3],[4,5,6]])
arr2=array([4,5,6])
arr3=array([[[1,2,3],[3,4,5],[6,7,8]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

2
1
3


In [34]:
#complex array
l=[1+3j,2+4j,5+7j]
arr=array(l,dtype=complex)
print(arr)
print(arr.dtype)

[1.+3.j 2.+4.j 5.+7.j]
complex128


In [35]:
#long-array
arr=arange(1,100000,1)
print(arr)

[    1     2     3 ... 99997 99998 99999]


In [36]:
#zero-array
arr=zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
#ones-array
print(ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#empty-array
print(empty(()))

1.0


In [44]:
#pi
print(pi)

3.141592653589793


In [47]:
#element wise addition
arr1=[[1,2,3],[4,5,6],[7,8,9]]
arr2=[[1,1,1],[1,1,1],[1,1,1]]
print(array(arr1)+array(arr2))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [48]:
#element wise multiplication
arr1=[[1,2,3],[4,5,6],[7,8,9]]
arr2=[[1,1,1],[1,1,1],[1,1,1]]
print(array(arr1)*array(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
#matric product
arr1=[[1,2,3],[4,5,6],[7,8,9]]
arr2=[[1,1,1],[1,1,1],[1,1,1]]
print(array(arr1)@array(arr2))

[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


In [55]:
#reshape
arr1=array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1)
print(arr1.shape)
new_arr=arr1.reshape(3,4)
print(new_arr)
print(new_arr.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [56]:
#sum of each column
arr1=array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1.sum(axis=0))

[22 26 30]


In [57]:
#sum of each row
arr1=array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1.sum(axis=1))

[ 6 15 24 33]


In [60]:
#min of each column
print(arr1.min(axis=0))

[1 2 3]


In [61]:
#max of each row
print(arr1.max(axis=1))

[ 3  6  9 12]


In [62]:
#cumulative sum along each row
print(arr1.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]
 [10 21 33]]


In [64]:
#cumulative sum alomg each column
print(arr1.cumsum(axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]
 [22 26 30]]


In [65]:
#constant array
print(full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [66]:
#identity matrix
print(eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
print(eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [76]:
#standard deviation using statistics
import statistics as st
arr=array([1,2,3,4,5])
print((st.stdev(arr)))
#using numpy
print(std(arr))

1.4142135623730951
1.4142135623730951


In [78]:
#diagonal-matrix
print(diag((1,2,3,4)))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [79]:
#eigen-values
print(linalg.eig(diag((1,2,3))))

(array([1., 2., 3.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [80]:
#co-variance
print(cov(arr1))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [81]:
#determinant
print(linalg.det(diag((1,2,3))))

6.0


In [82]:
#trace
print(trace(diag((1,2,3))))

6


In [87]:
#inverse 0f matrix
arr1=array([[1,2,3],[4,5,6],[7,8,9]])
print(inv(arr1))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
